// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA29vZDqzsinwsmYAqppYqJCzwaFyIr7VI',
    appId: '1:1044767177684:web:638a0b50fa49abdff83441',
    messagingSenderId: '1044767177684',
    projectId: 'jiranlinkapp',
    authDomain: 'jiranlinkapp.firebaseapp.com',
    storageBucket: 'jiranlinkapp.firebasestorage.app',
    measurementId: 'G-70GVQ63YPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdc55JLEHTbfyigljhcAQjEepnILcHqJY',
    appId: '1:1044767177684:android:9ff9c2fa7aa0dd7bf83441',
    messagingSenderId: '1044767177684',
    projectId: 'jiranlinkapp',
    storageBucket: 'jiranlinkapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0kniZMMRoNcDDiv40m-MMTZIWDSHImGc',
    appId: '1:1044767177684:ios:727ece1eb209139ef83441',
    messagingSenderId: '1044767177684',
    projectId: 'jiranlinkapp',
    storageBucket: 'jiranlinkapp.firebasestorage.app',
    iosBundleId: 'com.example.jiranlinkApp',
  );
}
